title: Penguin Class
description: International Penguin Class Dinghy Association
url: https://penguinclass.org
baseurl: ""
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
collections:
  events:
    output: true
    permalink: /events/:year/:month/:day/:basename/
  classifieds:
    output: true
    permalink: /classifieds/:year/:month/:day/:basename/
defaults:
  - scope: { path: "", type: posts }
    values: 
      layout: post
      permalink: /news/:year/:month/:day/:basename/
  - scope: { path: "", type: events }
    values: { layout: event }
  - scope: { path: "", type: classifieds }
    values: { layout: classified }
markdown: kramdown
